// ============================================================
// EduConnect Kanyakumari - Teachers & Students Mock Data
// ============================================================
import { Teacher, Student, Parent } from '@/lib/types';

export const teachers: Teacher[] = [
  { id: 'TCH001', employeeId: 'TN-KK-4521', name: 'Mr. S. Rajendran', gender: 'male', phone: '9876501001', email: 'rajendran.s@tn.gov.in', schoolId: 'SCH001', qualification: 'M.A., B.Ed.', specialization: 'Tamil', subjects: ['Tamil'], classesAssigned: ['10-A', '10-B', '11-A'], designation: 'Headmaster', joiningDate: '1998-06-15', experience: 28, isClassTeacher: false, isActive: true, address: 'Nagercoil, Kanyakumari' },
  { id: 'TCH002', employeeId: 'TN-KK-4522', name: 'Mrs. K. Ranjitha', gender: 'female', phone: '9876502001', email: 'ranjitha.k@tn.gov.in', schoolId: 'SCH001', qualification: 'M.Sc., B.Ed.', specialization: 'Mathematics', subjects: ['Mathematics'], classesAssigned: ['9-A', '9-B', '10-A'], designation: 'PG Assistant', joiningDate: '2005-07-10', experience: 21, isClassTeacher: true, classTeacherOf: '10-A', isActive: true, address: 'Asaripallam, Kanyakumari' },
  { id: 'TCH003', employeeId: 'TN-KK-4523', name: 'Mr. D. Arul Selvan', gender: 'male', phone: '9876502002', email: 'arulselvan.d@tn.gov.in', schoolId: 'SCH001', qualification: 'M.Sc., B.Ed.', specialization: 'Physics', subjects: ['Physics', 'Science'], classesAssigned: ['11-A', '11-B', '12-A'], designation: 'PG Assistant', joiningDate: '2008-06-20', experience: 18, isClassTeacher: true, classTeacherOf: '11-A', isActive: true, address: 'Nagercoil, Kanyakumari' },
  { id: 'TCH004', employeeId: 'TN-KK-4524', name: 'Mrs. P. Mercy', gender: 'female', phone: '9876502003', email: 'mercy.p@tn.gov.in', schoolId: 'SCH001', qualification: 'M.A., B.Ed.', specialization: 'English', subjects: ['English'], classesAssigned: ['9-A', '10-A', '10-B', '11-A'], designation: 'BT Assistant', joiningDate: '2010-07-05', experience: 16, isClassTeacher: true, classTeacherOf: '9-A', isActive: true, address: 'Kottar, Kanyakumari' },
  { id: 'TCH005', employeeId: 'TN-KK-4525', name: 'Mr. J. Christober', gender: 'male', phone: '9876502004', email: 'christober.j@tn.gov.in', schoolId: 'SCH001', qualification: 'M.Sc., B.Ed.', specialization: 'Chemistry', subjects: ['Chemistry', 'Science'], classesAssigned: ['11-B', '12-A', '12-B'], designation: 'PG Assistant', joiningDate: '2012-06-18', experience: 14, isClassTeacher: true, classTeacherOf: '12-A', isActive: true, address: 'Nagercoil, Kanyakumari' },
  { id: 'TCH006', employeeId: 'TN-KK-4526', name: 'Mrs. M. Tamilselvi', gender: 'female', phone: '9876502005', email: 'tamilselvi.m@tn.gov.in', schoolId: 'SCH001', qualification: 'M.Sc., B.Ed.', specialization: 'Biology', subjects: ['Biology', 'Zoology'], classesAssigned: ['11-A', '12-A', '12-B'], designation: 'PG Assistant', joiningDate: '2006-06-25', experience: 20, isClassTeacher: false, isActive: true, address: 'Vadasery, Kanyakumari' },
  { id: 'TCH007', employeeId: 'TN-KK-4527', name: 'Mr. R. Kalidoss', gender: 'male', phone: '9876502006', email: 'kalidoss.r@tn.gov.in', schoolId: 'SCH001', qualification: 'M.A., B.Ed.', specialization: 'History', subjects: ['History', 'Social Science'], classesAssigned: ['9-A', '9-B', '10-A', '10-B'], designation: 'BT Assistant', joiningDate: '2015-07-01', experience: 11, isClassTeacher: true, classTeacherOf: '9-B', isActive: true, address: 'Nagercoil, Kanyakumari' },
  { id: 'TCH008', employeeId: 'TN-KK-4528', name: 'Mrs. S. Angelin', gender: 'female', phone: '9876502007', email: 'angelin.s@tn.gov.in', schoolId: 'SCH001', qualification: 'M.Sc., M.Ed.', specialization: 'Computer Science', subjects: ['Computer Science'], classesAssigned: ['11-A', '11-B', '12-A', '12-B'], designation: 'PG Assistant', joiningDate: '2014-06-22', experience: 12, isClassTeacher: true, classTeacherOf: '11-B', isActive: true, address: 'Nagercoil, Kanyakumari' },
  { id: 'TCH009', employeeId: 'TN-KK-4529', name: 'Mr. A. Jayakumar', gender: 'male', phone: '9876502008', email: 'jayakumar.a@tn.gov.in', schoolId: 'SCH001', qualification: 'M.P.Ed.', specialization: 'Physical Education', subjects: ['Physical Education'], classesAssigned: ['9-A', '9-B', '10-A', '10-B', '11-A', '11-B'], designation: 'Physical Director', joiningDate: '2011-06-15', experience: 15, isClassTeacher: false, isActive: true, address: 'Nagercoil, Kanyakumari' },
  { id: 'TCH010', employeeId: 'TN-KK-4530', name: 'Mrs. V. Girija', gender: 'female', phone: '9876502009', email: 'girija.v@tn.gov.in', schoolId: 'SCH001', qualification: 'M.A., B.Ed.', specialization: 'Economics', subjects: ['Economics', 'Commerce'], classesAssigned: ['11-A', '11-B', '12-A'], designation: 'PG Assistant', joiningDate: '2009-07-10', experience: 17, isClassTeacher: true, classTeacherOf: '10-B', isActive: true, address: 'Nagercoil, Kanyakumari' },
  { id: 'TCH011', employeeId: 'TN-KK-4531', name: 'Mr. L. Bennet', gender: 'male', phone: '9876502010', email: 'bennet.l@tn.gov.in', schoolId: 'SCH001', qualification: 'M.A., B.Ed.', specialization: 'Geography', subjects: ['Geography', 'Social Science'], classesAssigned: ['9-A', '9-B', '10-A'], designation: 'BT Assistant', joiningDate: '2016-06-20', experience: 10, isClassTeacher: false, isActive: true, address: 'Nagercoil, Kanyakumari' },
  { id: 'TCH012', employeeId: 'TN-KK-4532', name: 'Mrs. N. Kavitha', gender: 'female', phone: '9876502011', email: 'kavitha.n@tn.gov.in', schoolId: 'SCH001', qualification: 'M.Sc., B.Ed.', specialization: 'Mathematics', subjects: ['Mathematics'], classesAssigned: ['6-A', '7-A', '8-A'], designation: 'BT Assistant', joiningDate: '2018-07-05', experience: 8, isClassTeacher: true, classTeacherOf: '8-A', isActive: true, address: 'Nagercoil, Kanyakumari' },
];

export const students: Student[] = [
  { id: 'STU001', emisId: 'TN2024KK00001', name: 'Arun Kumar S', gender: 'male', dateOfBirth: '2010-03-15', className: '10', section: 'A', rollNumber: 1, schoolId: 'SCH001', parentId: 'PAR001', parentName: 'Mr. Suresh Kumar', parentPhone: '9876601001', address: 'Nagercoil, Kanyakumari', medium: 'Tamil', community: 'BC', isActive: true, admissionDate: '2020-06-15', scholarships: ['State Merit Scholarship'] },
  { id: 'STU002', emisId: 'TN2024KK00002', name: 'Divya Lakshmi M', gender: 'female', dateOfBirth: '2010-07-22', className: '10', section: 'A', rollNumber: 2, schoolId: 'SCH001', parentId: 'PAR002', parentName: 'Mr. Murugan R', parentPhone: '9876601002', address: 'Kottar, Kanyakumari', medium: 'Tamil', community: 'MBC', isActive: true, admissionDate: '2020-06-15' },
  { id: 'STU003', emisId: 'TN2024KK00003', name: 'Karthik Raja V', gender: 'male', dateOfBirth: '2010-01-08', className: '10', section: 'A', rollNumber: 3, schoolId: 'SCH001', parentId: 'PAR003', parentName: 'Mr. Vel Murugan', parentPhone: '9876601003', address: 'Vadasery, Kanyakumari', medium: 'Tamil', community: 'BC', isActive: true, admissionDate: '2020-06-16' },
  { id: 'STU004', emisId: 'TN2024KK00004', name: 'Meena Kumari P', gender: 'female', dateOfBirth: '2010-11-30', className: '10', section: 'A', rollNumber: 4, schoolId: 'SCH001', parentId: 'PAR004', parentName: 'Mr. Pandian S', parentPhone: '9876601004', address: 'Asaripallam, Kanyakumari', medium: 'Tamil', community: 'SC', isActive: true, admissionDate: '2020-06-16', scholarships: ['SC/ST Scholarship'] },
  { id: 'STU005', emisId: 'TN2024KK00005', name: 'Prasanth J', gender: 'male', dateOfBirth: '2010-05-14', className: '10', section: 'A', rollNumber: 5, schoolId: 'SCH001', parentId: 'PAR005', parentName: 'Mr. Jayakumar N', parentPhone: '9876601005', address: 'Nagercoil, Kanyakumari', medium: 'Tamil', community: 'BC', isActive: true, admissionDate: '2020-06-17' },
  { id: 'STU006', emisId: 'TN2024KK00006', name: 'Roshini S', gender: 'female', dateOfBirth: '2010-09-03', className: '10', section: 'A', rollNumber: 6, schoolId: 'SCH001', parentId: 'PAR006', parentName: 'Mr. Selvam K', parentPhone: '9876601006', address: 'Nagercoil, Kanyakumari', medium: 'Tamil', community: 'MBC', isActive: true, admissionDate: '2020-06-17' },
  { id: 'STU007', emisId: 'TN2024KK00007', name: 'Surya Prakash A', gender: 'male', dateOfBirth: '2010-02-28', className: '10', section: 'B', rollNumber: 1, schoolId: 'SCH001', parentId: 'PAR007', parentName: 'Mr. Arul Raj', parentPhone: '9876601007', address: 'Kottar, Kanyakumari', medium: 'Tamil', community: 'BC', isActive: true, admissionDate: '2020-06-15' },
  { id: 'STU008', emisId: 'TN2024KK00008', name: 'Tamil Selvi R', gender: 'female', dateOfBirth: '2010-12-10', className: '10', section: 'B', rollNumber: 2, schoolId: 'SCH001', parentId: 'PAR008', parentName: 'Mr. Rajesh P', parentPhone: '9876601008', address: 'Nagercoil, Kanyakumari', medium: 'Tamil', community: 'OC', isActive: true, admissionDate: '2020-06-15' },
  { id: 'STU009', emisId: 'TN2024KK00009', name: 'Vignesh Kumar T', gender: 'male', dateOfBirth: '2011-04-19', className: '9', section: 'A', rollNumber: 1, schoolId: 'SCH001', parentId: 'PAR009', parentName: 'Mr. Thangaraj K', parentPhone: '9876601009', address: 'Vadasery, Kanyakumari', medium: 'Tamil', community: 'BC', isActive: true, admissionDate: '2021-06-14' },
  { id: 'STU010', emisId: 'TN2024KK00010', name: 'Yamuna Devi S', gender: 'female', dateOfBirth: '2011-08-05', className: '9', section: 'A', rollNumber: 2, schoolId: 'SCH001', parentId: 'PAR010', parentName: 'Mr. Sundar Raj', parentPhone: '9876601010', address: 'Asaripallam, Kanyakumari', medium: 'Tamil', community: 'MBC', isActive: true, admissionDate: '2021-06-14' },
  { id: 'STU011', emisId: 'TN2024KK00011', name: 'Ashwin R', gender: 'male', dateOfBirth: '2011-06-12', className: '9', section: 'A', rollNumber: 3, schoolId: 'SCH001', parentId: 'PAR011', parentName: 'Mr. Ramesh V', parentPhone: '9876601011', address: 'Nagercoil, Kanyakumari', medium: 'Tamil', community: 'BC', isActive: true, admissionDate: '2021-06-15' },
  { id: 'STU012', emisId: 'TN2024KK00012', name: 'Bharathi M', gender: 'female', dateOfBirth: '2011-10-25', className: '9', section: 'A', rollNumber: 4, schoolId: 'SCH001', parentId: 'PAR012', parentName: 'Mr. Manikandan S', parentPhone: '9876601012', address: 'Nagercoil, Kanyakumari', medium: 'Tamil', community: 'SC', isActive: true, admissionDate: '2021-06-15', scholarships: ['SC/ST Scholarship'] },
  { id: 'STU013', emisId: 'TN2024KK00013', name: 'Deepak Kumar L', gender: 'male', dateOfBirth: '2012-01-17', className: '8', section: 'A', rollNumber: 1, schoolId: 'SCH001', parentId: 'PAR013', parentName: 'Mr. Lakshmanan P', parentPhone: '9876601013', address: 'Nagercoil, Kanyakumari', medium: 'Tamil', community: 'BC', isActive: true, admissionDate: '2022-06-14' },
  { id: 'STU014', emisId: 'TN2024KK00014', name: 'Gayathri S', gender: 'female', dateOfBirth: '2012-04-08', className: '8', section: 'A', rollNumber: 2, schoolId: 'SCH001', parentId: 'PAR014', parentName: 'Mr. Srinivasan K', parentPhone: '9876601014', address: 'Kottar, Kanyakumari', medium: 'Tamil', community: 'OC', isActive: true, admissionDate: '2022-06-14' },
  { id: 'STU015', emisId: 'TN2024KK00015', name: 'Harish Babu N', gender: 'male', dateOfBirth: '2012-07-20', className: '8', section: 'A', rollNumber: 3, schoolId: 'SCH001', parentId: 'PAR015', parentName: 'Mr. Nagarajan V', parentPhone: '9876601015', address: 'Vadasery, Kanyakumari', medium: 'Tamil', community: 'MBC', isActive: true, admissionDate: '2022-06-15' },
  { id: 'STU016', emisId: 'TN2024KK00016', name: 'Indhu Mathi K', gender: 'female', dateOfBirth: '2013-02-14', className: '7', section: 'A', rollNumber: 1, schoolId: 'SCH001', parentId: 'PAR016', parentName: 'Mr. Kannan M', parentPhone: '9876601016', address: 'Nagercoil, Kanyakumari', medium: 'Tamil', community: 'BC', isActive: true, admissionDate: '2023-06-12' },
  { id: 'STU017', emisId: 'TN2024KK00017', name: 'Jeeva Prakash S', gender: 'male', dateOfBirth: '2013-05-30', className: '7', section: 'A', rollNumber: 2, schoolId: 'SCH001', parentId: 'PAR017', parentName: 'Mr. Subramanian R', parentPhone: '9876601017', address: 'Nagercoil, Kanyakumari', medium: 'Tamil', community: 'BC', isActive: true, admissionDate: '2023-06-12' },
  { id: 'STU018', emisId: 'TN2024KK00018', name: 'Keerthana V', gender: 'female', dateOfBirth: '2014-09-11', className: '6', section: 'A', rollNumber: 1, schoolId: 'SCH001', parentId: 'PAR018', parentName: 'Mr. Vijayakumar T', parentPhone: '9876601018', address: 'Asaripallam, Kanyakumari', medium: 'Tamil', community: 'MBC', isActive: true, admissionDate: '2024-06-10' },
  { id: 'STU019', emisId: 'TN2024KK00019', name: 'Logesh Kumar M', gender: 'male', dateOfBirth: '2014-11-25', className: '6', section: 'A', rollNumber: 2, schoolId: 'SCH001', parentId: 'PAR019', parentName: 'Mr. Mohan K', parentPhone: '9876601019', address: 'Nagercoil, Kanyakumari', medium: 'Tamil', community: 'SC', isActive: true, admissionDate: '2024-06-10', scholarships: ['SC/ST Scholarship'] },
  { id: 'STU020', emisId: 'TN2024KK00020', name: 'Nithya Sri P', gender: 'female', dateOfBirth: '2014-06-18', className: '6', section: 'A', rollNumber: 3, schoolId: 'SCH001', parentId: 'PAR020', parentName: 'Mr. Pandian K', parentPhone: '9876601020', address: 'Nagercoil, Kanyakumari', medium: 'Tamil', community: 'BC', isActive: true, admissionDate: '2024-06-11' },
];

export const parents: Parent[] = [
  { id: 'PAR001', name: 'Mr. Suresh Kumar', phone: '9876601001', email: 'suresh.k@gmail.com', occupation: 'Agriculture', address: 'Nagercoil, Kanyakumari', studentIds: ['STU001'], isActive: true },
  { id: 'PAR002', name: 'Mr. Murugan R', phone: '9876601002', occupation: 'Auto Driver', address: 'Kottar, Kanyakumari', studentIds: ['STU002'], isActive: true },
  { id: 'PAR003', name: 'Mr. Vel Murugan', phone: '9876601003', occupation: 'Shop Owner', address: 'Vadasery, Kanyakumari', studentIds: ['STU003'], isActive: true },
  { id: 'PAR004', name: 'Mr. Pandian S', phone: '9876601004', occupation: 'Daily Wage Worker', address: 'Asaripallam, Kanyakumari', studentIds: ['STU004'], isActive: true },
  { id: 'PAR005', name: 'Mr. Jayakumar N', phone: '9876601005', email: 'jayakumar.n@gmail.com', occupation: 'Government Employee', address: 'Nagercoil, Kanyakumari', studentIds: ['STU005'], isActive: true },
  { id: 'PAR006', name: 'Mr. Selvam K', phone: '9876601006', occupation: 'Fisherman', address: 'Nagercoil, Kanyakumari', studentIds: ['STU006'], isActive: true },
  { id: 'PAR007', name: 'Mr. Arul Raj', phone: '9876601007', occupation: 'Carpenter', address: 'Kottar, Kanyakumari', studentIds: ['STU007'], isActive: true },
  { id: 'PAR008', name: 'Mr. Rajesh P', phone: '9876601008', email: 'rajesh.p@gmail.com', occupation: 'Teacher', address: 'Nagercoil, Kanyakumari', studentIds: ['STU008'], isActive: true },
  { id: 'PAR009', name: 'Mr. Thangaraj K', phone: '9876601009', occupation: 'Agriculture', address: 'Vadasery, Kanyakumari', studentIds: ['STU009'], isActive: true },
  { id: 'PAR010', name: 'Mr. Sundar Raj', phone: '9876601010', occupation: 'Mason', address: 'Asaripallam, Kanyakumari', studentIds: ['STU010'], isActive: true },
];

export const getTeacherById = (id: string): Teacher | undefined => teachers.find((t) => t.id === id);
export const getTeachersBySchool = (schoolId: string): Teacher[] => teachers.filter((t) => t.schoolId === schoolId);
export const getStudentById = (id: string): Student | undefined => students.find((s) => s.id === id);
export const getStudentsByClass = (className: string, section: string, schoolId: string): Student[] =>
  students.filter((s) => s.className === className && s.section === section && s.schoolId === schoolId);
export const getParentById = (id: string): Parent | undefined => parents.find((p) => p.id === id);
