// ============================================================
// EduConnect Kanyakumari - Schools Mock Data
// ============================================================
import { School } from '@/lib/types';

export const schools: School[] = [
  {
    id: 'SCH001', name: 'Government Higher Secondary School, Nagercoil', udiseCode: '33140100101',
    type: 'Government Higher Secondary School', districtId: 'DST001', blockId: 'BLK001',
    address: 'Main Road, Nagercoil, Kanyakumari - 629001', pincode: '629001',
    phone: '04652-230001', email: 'ghss.nagercoil@tn.gov.in',
    principalName: 'Mr. S. Rajendran', principalPhone: '9876501001',
    medium: ['Tamil', 'English'], classesFrom: 6, classesTo: 12,
    totalStudents: 1250, totalTeachers: 68, totalClassrooms: 35,
    hasLibrary: true, hasLab: true, hasPlayground: true, hasComputer: true,
    hasInternet: true, hasMidDayMeal: true, hasToilets: true, hasDrinkingWater: true, hasRamp: true,
    establishedYear: 1952, lastInspection: '2025-11-15', complianceStatus: 'compliant', healthScore: 92,
  },
  {
    id: 'SCH002', name: 'Government Girls Higher Secondary School, Nagercoil', udiseCode: '33140100102',
    type: 'Government Higher Secondary School', districtId: 'DST001', blockId: 'BLK001',
    address: 'Court Road, Nagercoil, Kanyakumari - 629001', pincode: '629001',
    phone: '04652-230002', email: 'gghss.nagercoil@tn.gov.in',
    principalName: 'Mrs. M. Tamilselvi', principalPhone: '9876501002',
    medium: ['Tamil'], classesFrom: 6, classesTo: 12,
    totalStudents: 980, totalTeachers: 52, totalClassrooms: 28,
    hasLibrary: true, hasLab: true, hasPlayground: true, hasComputer: true,
    hasInternet: true, hasMidDayMeal: true, hasToilets: true, hasDrinkingWater: true, hasRamp: true,
    establishedYear: 1965, lastInspection: '2025-10-22', complianceStatus: 'compliant', healthScore: 89,
  },
  {
    id: 'SCH003', name: 'Government Higher Secondary School, Marthandam', udiseCode: '33140200101',
    type: 'Government Higher Secondary School', districtId: 'DST001', blockId: 'BLK002',
    address: 'Bypass Road, Marthandam, Kanyakumari - 629165', pincode: '629165',
    phone: '04652-270001', email: 'ghss.marthandam@tn.gov.in',
    principalName: 'Mr. V. Christudas', principalPhone: '9876501003',
    medium: ['Tamil', 'English'], classesFrom: 6, classesTo: 12,
    totalStudents: 1100, totalTeachers: 58, totalClassrooms: 30,
    hasLibrary: true, hasLab: true, hasPlayground: true, hasComputer: true,
    hasInternet: true, hasMidDayMeal: true, hasToilets: true, hasDrinkingWater: true, hasRamp: false,
    establishedYear: 1958, lastInspection: '2025-09-18', complianceStatus: 'compliant', healthScore: 87,
  },
  {
    id: 'SCH004', name: 'Government High School, Colachel', udiseCode: '33140300101',
    type: 'Government High School', districtId: 'DST001', blockId: 'BLK003',
    address: 'Beach Road, Colachel, Kanyakumari - 629251', pincode: '629251',
    phone: '04652-252001', email: 'ghs.colachel@tn.gov.in',
    principalName: 'Mrs. L. Jeyalakshmi', principalPhone: '9876501004',
    medium: ['Tamil'], classesFrom: 6, classesTo: 10,
    totalStudents: 680, totalTeachers: 38, totalClassrooms: 20,
    hasLibrary: true, hasLab: true, hasPlayground: true, hasComputer: true,
    hasInternet: false, hasMidDayMeal: true, hasToilets: true, hasDrinkingWater: true, hasRamp: true,
    establishedYear: 1972, lastInspection: '2025-08-10', complianceStatus: 'partial', healthScore: 78,
  },
  {
    id: 'SCH005', name: 'Government Higher Secondary School, Padmanabhapuram', udiseCode: '33140500101',
    type: 'Government Higher Secondary School', districtId: 'DST001', blockId: 'BLK005',
    address: 'Palace Road, Padmanabhapuram, Kanyakumari - 629175', pincode: '629175',
    phone: '04652-260001', email: 'ghss.padmanabhapuram@tn.gov.in',
    principalName: 'Mr. A. Subramaniam', principalPhone: '9876501005',
    medium: ['Tamil', 'English'], classesFrom: 6, classesTo: 12,
    totalStudents: 920, totalTeachers: 48, totalClassrooms: 26,
    hasLibrary: true, hasLab: true, hasPlayground: true, hasComputer: true,
    hasInternet: true, hasMidDayMeal: true, hasToilets: true, hasDrinkingWater: true, hasRamp: true,
    establishedYear: 1948, lastInspection: '2025-12-05', complianceStatus: 'compliant', healthScore: 94,
  },
  {
    id: 'SCH006', name: 'ADW Higher Secondary School, Arumanai', udiseCode: '33140400101',
    type: 'Adi Dravidar Welfare School', districtId: 'DST001', blockId: 'BLK004',
    address: 'Main Road, Arumanai, Kanyakumari - 629151', pincode: '629151',
    phone: '04652-240001', email: 'adwhss.arumanai@tn.gov.in',
    principalName: 'Mrs. P. Vasanthi', principalPhone: '9876501006',
    medium: ['Tamil'], classesFrom: 6, classesTo: 12,
    totalStudents: 540, totalTeachers: 32, totalClassrooms: 18,
    hasLibrary: true, hasLab: true, hasPlayground: false, hasComputer: true,
    hasInternet: false, hasMidDayMeal: true, hasToilets: true, hasDrinkingWater: true, hasRamp: false,
    establishedYear: 1980, lastInspection: '2025-07-20', complianceStatus: 'partial', healthScore: 72,
  },
  {
    id: 'SCH007', name: 'Government Middle School, Suchindram', udiseCode: '33140100201',
    type: 'Government Middle School', districtId: 'DST001', blockId: 'BLK001',
    address: 'Temple Street, Suchindram, Kanyakumari - 629704', pincode: '629704',
    phone: '04652-235001', email: 'gms.suchindram@tn.gov.in',
    principalName: 'Mr. K. Baskaran', principalPhone: '9876501007',
    medium: ['Tamil'], classesFrom: 6, classesTo: 8,
    totalStudents: 280, totalTeachers: 18, totalClassrooms: 10,
    hasLibrary: true, hasLab: false, hasPlayground: true, hasComputer: true,
    hasInternet: false, hasMidDayMeal: true, hasToilets: true, hasDrinkingWater: true, hasRamp: false,
    establishedYear: 1988, lastInspection: '2025-06-15', complianceStatus: 'compliant', healthScore: 80,
  },
  {
    id: 'SCH008', name: 'Government Primary School, Kottaram', udiseCode: '33140100301',
    type: 'Government Primary School', districtId: 'DST001', blockId: 'BLK001',
    address: 'Kottaram, Nagercoil, Kanyakumari - 629002', pincode: '629002',
    phone: '04652-232001', email: 'gps.kottaram@tn.gov.in',
    principalName: 'Mrs. S. Amudha', principalPhone: '9876501008',
    medium: ['Tamil'], classesFrom: 1, classesTo: 5,
    totalStudents: 180, totalTeachers: 12, totalClassrooms: 8,
    hasLibrary: false, hasLab: false, hasPlayground: true, hasComputer: false,
    hasInternet: false, hasMidDayMeal: true, hasToilets: true, hasDrinkingWater: true, hasRamp: false,
    establishedYear: 1995, lastInspection: '2025-05-10', complianceStatus: 'partial', healthScore: 68,
  },
  {
    id: 'SCH009', name: 'Government Higher Secondary School, Kuzhithurai', udiseCode: '33140300201',
    type: 'Government Higher Secondary School', districtId: 'DST001', blockId: 'BLK003',
    address: 'Kuzhithurai Main Road, Kanyakumari - 629163', pincode: '629163',
    phone: '04651-220001', email: 'ghss.kuzhithurai@tn.gov.in',
    principalName: 'Mr. D. Alexander', principalPhone: '9876501009',
    medium: ['Tamil', 'English'], classesFrom: 6, classesTo: 12,
    totalStudents: 1050, totalTeachers: 55, totalClassrooms: 28,
    hasLibrary: true, hasLab: true, hasPlayground: true, hasComputer: true,
    hasInternet: true, hasMidDayMeal: true, hasToilets: true, hasDrinkingWater: true, hasRamp: true,
    establishedYear: 1960, lastInspection: '2025-11-28', complianceStatus: 'compliant', healthScore: 90,
  },
  {
    id: 'SCH010', name: 'Government High School, Eraniel', udiseCode: '33140200201',
    type: 'Government High School', districtId: 'DST001', blockId: 'BLK002',
    address: 'Eraniel Junction, Kanyakumari - 629802', pincode: '629802',
    phone: '04652-272001', email: 'ghs.eraniel@tn.gov.in',
    principalName: 'Mrs. R. Selvarani', principalPhone: '9876501010',
    medium: ['Tamil'], classesFrom: 6, classesTo: 10,
    totalStudents: 520, totalTeachers: 30, totalClassrooms: 16,
    hasLibrary: true, hasLab: true, hasPlayground: true, hasComputer: true,
    hasInternet: false, hasMidDayMeal: true, hasToilets: true, hasDrinkingWater: true, hasRamp: false,
    establishedYear: 1975, lastInspection: '2025-09-05', complianceStatus: 'compliant', healthScore: 82,
  },
  {
    id: 'SCH011', name: 'Municipal High School, Nagercoil', udiseCode: '33140100401',
    type: 'Municipal School', districtId: 'DST001', blockId: 'BLK001',
    address: 'Duthie School Road, Nagercoil - 629001', pincode: '629001',
    phone: '04652-231001', email: 'mhs.nagercoil@tn.gov.in',
    principalName: 'Mr. M. Jeyapaul', principalPhone: '9876501011',
    medium: ['Tamil', 'English'], classesFrom: 6, classesTo: 10,
    totalStudents: 420, totalTeachers: 24, totalClassrooms: 14,
    hasLibrary: true, hasLab: false, hasPlayground: false, hasComputer: true,
    hasInternet: true, hasMidDayMeal: true, hasToilets: true, hasDrinkingWater: true, hasRamp: true,
    establishedYear: 1982, lastInspection: '2025-10-12', complianceStatus: 'partial', healthScore: 75,
  },
  {
    id: 'SCH012', name: 'Government Higher Secondary School, Thuckalay', udiseCode: '33140600101',
    type: 'Government Higher Secondary School', districtId: 'DST001', blockId: 'BLK006',
    address: 'Thuckalay, Kanyakumari - 629175', pincode: '629175',
    phone: '04651-250001', email: 'ghss.thuckalay@tn.gov.in',
    principalName: 'Mrs. G. Jancy', principalPhone: '9876501012',
    medium: ['Tamil'], classesFrom: 6, classesTo: 12,
    totalStudents: 880, totalTeachers: 46, totalClassrooms: 24,
    hasLibrary: true, hasLab: true, hasPlayground: true, hasComputer: true,
    hasInternet: true, hasMidDayMeal: true, hasToilets: true, hasDrinkingWater: true, hasRamp: true,
    establishedYear: 1955, lastInspection: '2025-10-30', complianceStatus: 'compliant', healthScore: 88,
  },
  {
    id: 'SCH013', name: 'Government High School, Melpuram', udiseCode: '33140700101',
    type: 'Government High School', districtId: 'DST001', blockId: 'BLK007',
    address: 'Melpuram, Kanyakumari - 629180', pincode: '629180',
    phone: '04651-260001', email: 'ghs.melpuram@tn.gov.in',
    principalName: 'Mr. T. Johnson', principalPhone: '9876501013',
    medium: ['Tamil'], classesFrom: 6, classesTo: 10,
    totalStudents: 390, totalTeachers: 22, totalClassrooms: 12,
    hasLibrary: true, hasLab: false, hasPlayground: true, hasComputer: true,
    hasInternet: false, hasMidDayMeal: true, hasToilets: true, hasDrinkingWater: true, hasRamp: false,
    establishedYear: 1990, lastInspection: '2025-08-25', complianceStatus: 'compliant', healthScore: 79,
  },
  {
    id: 'SCH014', name: 'Government Higher Secondary School, Kanyakumari', udiseCode: '33140100501',
    type: 'Government Higher Secondary School', districtId: 'DST001', blockId: 'BLK001',
    address: 'Vivekananda Road, Kanyakumari - 629702', pincode: '629702',
    phone: '04652-246001', email: 'ghss.kanyakumari@tn.gov.in',
    principalName: 'Dr. N. Vijayakumar', principalPhone: '9876501014',
    medium: ['Tamil', 'English'], classesFrom: 6, classesTo: 12,
    totalStudents: 760, totalTeachers: 42, totalClassrooms: 22,
    hasLibrary: true, hasLab: true, hasPlayground: true, hasComputer: true,
    hasInternet: true, hasMidDayMeal: true, hasToilets: true, hasDrinkingWater: true, hasRamp: true,
    establishedYear: 1945, lastInspection: '2025-12-10', complianceStatus: 'compliant', healthScore: 91,
  },
  {
    id: 'SCH015', name: 'Government Primary School, Boothapandi', udiseCode: '33140800101',
    type: 'Government Primary School', districtId: 'DST001', blockId: 'BLK008',
    address: 'Boothapandi, Kurunthancode, Kanyakumari - 629201', pincode: '629201',
    phone: '04651-270001', email: 'gps.boothapandi@tn.gov.in',
    principalName: 'Mrs. J. Latha', principalPhone: '9876501015',
    medium: ['Tamil'], classesFrom: 1, classesTo: 5,
    totalStudents: 145, totalTeachers: 9, totalClassrooms: 6,
    hasLibrary: false, hasLab: false, hasPlayground: true, hasComputer: false,
    hasInternet: false, hasMidDayMeal: true, hasToilets: true, hasDrinkingWater: true, hasRamp: false,
    establishedYear: 2001, lastInspection: '2025-04-15', complianceStatus: 'partial', healthScore: 65,
  },
];

export const getSchoolById = (id: string): School | undefined =>
  schools.find((s) => s.id === id);

export const getSchoolsByBlock = (blockId: string): School[] =>
  schools.filter((s) => s.blockId === blockId);

export const getSchoolsByDistrict = (districtId: string): School[] =>
  schools.filter((s) => s.districtId === districtId);

export const getPrimarySchool = (): School => schools[0]; // Default demo school
